server:
  port: 8000

logger:
  level: debug

sources:
  - id: countries
    type: graphql
    config:
      endpoint: ${COUNTRIES_ENDPOINT:https://countries.trevorblades.com/}

endpoints:
  - path: /graphql
    from: countries
    plugins:
      - type: cors
        config:
          allow_credentials: true
          allowed_methods:
            - GET
            - POST
          allowed_origin: https://example.com
          allowed_headers:
            - Content-Type
            - Authorization
          allow_private_network: false
          max_age: 3600

  - path: /persisted
    from: countries
    plugins:
      - type: persisted_operations
        config:
          store:
            source: file
            path: ../test_config/persisted_operations_store.json
            format: json_key_value
          protocols:
            - type: apollo_manifest_extensions
            - type: document_id
            - type: http_get
              document_id_from:
                source: search_query
                name: docId
              variables_from:
                source: header
                name: 'X-GraphQL-Variables'
          allow_non_persisted: true

  - path: /test
    from: countries
    plugins:
      - type: graphiql
      - type: http_get
        config:
          mutations: false
