server:
  port: 9000

logger:
  level: debug
  format: pretty

sources:
  - id: countries
    type: graphql
    config:
      endpoint: https://countries.trevorblades.com/
  - id: fed
    type: federation
    config:
      file_path: ./query_planner/supergraph.graphql

endpoints:
  - path: /graphql
    from: countries

  - path: /test
    from: countries

  - path: /federation
    from: fed
