server:
  port: 9000

logger:
  level: error
  format: pretty

sources:
  - id: countries
    type: graphql
    config:
      endpoint: http://localhost:4000/graphql

endpoints:
  - path: /graphql
    from: countries

  - path: /test
    from: countries
