name: benchmark

on:
  pull_request:
    paths-ignore:
      - "website/**"

jobs:
  criterion:
    name: criterion
    runs-on: ubuntu-22.04
    steps:
      - name: checkout ${{ github.base_ref }}
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          ref: ${{ github.base_ref }}

      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy
          override: true

      - name: measure benchmarks on ${{ github.base_ref }}
        run: cargo bench
        working-directory: libs/benches

      - name: checkout PR
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          clean: false

      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy
          override: true

      - name: measure benchmarks on PR
        run: cargo bench
        working-directory: libs/benches

      - name: upload benchmark report
        uses: actions/upload-artifact@v4
        with:
          name: Criterion Report
          path: target/criterion/

  k6:
    name: k6
    env:
      K6_VERSION: 0.48.0
    # runs-on: ubuntu-22.04
    runs-on: benchmark-runner
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions-rs/toolchain@v1
        with:
          override: true

      - name: Setup K6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6=${{ env.K6_VERSION }}

      - name: figure out versions
        id: versions
        working-directory: ./benchmark
        run:
          PNPM_VERSION=$(cat package.json | jq -r '.packageManager' | awk -F@ '{print $2}')
          NODE_VERSION=$(cat package.json | jq -r '.engines.node' | awk -F= '{print $2}')

          echo "pnpm=$PNPM_VERSION" >> $GITHUB_OUTPUT
          echo "nodejs=$NODE_VERSION" >> $GITHUB_OUTPUT

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: ${{ steps.versions.outputs.nodejs }}
          packageManager: pnpm
          packageManagerVersion: ${{ steps.versions.outputs.pnpm }}
          workingDirectory: ./benchmark

      - name: "build release binary"
        run: cargo build --bin conductor --release

      - name: run k6
        run: pnpm test
        working-directory: benchmark
        env:
          GITHUB_PR: ${{ github.event.number }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_NO_WARNINGS: true
          NODE_ENV: production
