name: release

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build / ${{ matrix.platform.target }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu

          - os: ubuntu-22.04
            target: aarch64-unknown-linux-gnu

          - os: ubuntu-22.04
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - uses: actions/upload-artifact@v3
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
        with:
          name: conductor-${{ matrix.platform.target }}
          path: target/${{ matrix.platform.target }}/release/conductor
